mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.152.0"

replicaCount: 1

serviceAccount:
  create: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

useGOMEMLIMIT: true

ports:
  otlp:
    enabled: false
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

service:
  type: ClusterIP

config:
  receivers:
    kafka:
      brokers:
        - automq-kafka.automq.svc.cluster.local:9092
      client_id: otel-kafka-consumer
      group_id: otel-kafka-consumer
      logs:
        topics:
          - otel-logs
        encoding: otlp_json
      metrics:
        topics:
          - otel-metrics
        encoding: otlp_json
      traces:
        topics:
          - otel-traces
        encoding: otlp_json
      auth:
        sasl:
          username: user1
          password: FeOayikYWD
          mechanism: SCRAM-SHA-256

  processors:
    resource/kafka_pipeline:
      attributes:
        - key: messaging.system
          value: kafka
          action: insert
        - key: telemetry.pipeline.name
          value: otel-kafka-consumer
          action: insert
        - key: telemetry.pipeline.stage
          value: kafka-consumer
          action: insert

    batch:
      timeout: 10s
      send_batch_size: 5000
      send_batch_max_size: 10000

  exporters:
    clickhouse:
      endpoint: tcp://clickhouse-clickhouse.clickhouse.svc.cluster.local:9000
      database: default
      username: admin_user
      password: clickhouse_admin_password
      timeout: 30s
      create_schema: false
      json: true
      # logs_table_name: otel_logs
      # traces_table_name: otel_traces
      connection_params:
        enable_json_type: "1"
      retry_on_failure:
        enabled: true
        initial_interval: 5s
        max_interval: 30s
        max_elapsed_time: 600s
      sending_queue:
        enabled: true
        num_consumers: 10
        queue_size: 5000

  service:
    pipelines:
      metrics:
        receivers: [kafka]
        processors: [resource/kafka_pipeline, batch]
        exporters: [clickhouse]
      traces:
        receivers: [kafka]
        processors: [resource/kafka_pipeline, batch]
        exporters: [clickhouse]
      logs:
        receivers: [kafka]
        processors: [resource/kafka_pipeline, batch]
        exporters: [clickhouse]
