apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://rancher.gabrielcarvalho.dev/k8s/clusters/local
  name: local
contexts:
- context:
    cluster: local
    user: local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: local
  user:
    token: kubeconfig-user-wkrzhwgbw2:2ldpmgrwk7g292x2l5wncmw548dlmdmtjdk8c9vwk7xpb5j2snb8xn
