apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-crd-node-config
  namespace: otel-crd-node
data:
  POSTGRES_URL: "postgresql://app_user:app_password@192.168.1.3:5455/loglog"
  REDIS_URL: "192.168.1.3:6379"
  PORT: "80"